version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "3f:f7:43:b1:de:22:3e:5b:7a:28:ef:9d:73:a7:a7:59"
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.11/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.11/site-packages"
      - run:
          command: |
            make ssh_upload
workflows:
  version: 2
  manual:
    jobs:
      - build:
          filters:
            branches:
              only:
                - manual
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
